# Generated by Django 4.2.3 on 2023-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Form',
            },
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='image',
            field=models.ImageField(upload_to='blogpro'),
        ),
    ]
